export { default, SCHOOL, THEME, OFFICE, PROGRAMS, DEPARTMENTS, ALL_COURSES, COURSE_DEPARTMENT_MAP, DEPARTMENT_COURSE_MAP, MANUAL_PROCESSES, ABBREVIATIONS, SYSTEM } from './trac.config.js';
export { default as TRAC_CONFIG } from './trac.config.js';
